# Generated by Django 5.2.7 on 2025-10-03 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="room",
            name="current_round",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="max_players",
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="room",
            name="phase",
            field=models.CharField(
                choices=[
                    ("lobby", "大厅"),
                    ("prepare", "准备阶段"),
                    ("playing", "游戏中"),
                    ("review", "总结"),
                ],
                default="lobby",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "等待中"),
                    ("in_progress", "进行中"),
                    ("completed", "已结束"),
                    ("closed", "已解散"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="RoomPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("seat_number", models.PositiveIntegerField()),
                ("is_host", models.BooleanField(default=False)),
                ("is_ai", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(blank=True, max_length=40)),
                ("word", models.CharField(blank=True, max_length=120)),
                ("is_alive", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "房间成员",
                "verbose_name_plural": "房间成员",
                "ordering": ("seat_number", "joined_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "seat_number"), name="unique_room_seat"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("room", "user"),
                        name="unique_room_user",
                    ),
                ],
            },
        ),
    ]
