# Generated by Django 5.2.7 on 2025-10-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_config_room_current_round_room_max_players_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomplayer",
            name="has_used_skill",
            field=models.BooleanField(default=False),
        ),
    ]
