# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_roomplayer_has_used_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomplayer",
            name="ai_style",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
