# Generated by Django 5.2.7 on 2025-10-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssistantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "AI 助手配置",
                "verbose_name_plural": "AI 助手配置",
            },
        ),
    ]
