# Generated by Django 5.2.7 on 2025-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamecore", "0003_extend_gamesession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamesession",
            options={
                "ordering": ("-started_at",),
                "verbose_name": "游戏会话",
                "verbose_name_plural": "游戏会话",
            },
        ),
        migrations.AddField(
            model_name="gamesession",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="timer_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
